# PCA implemention step by step

In [1]:
# imports
import numpy as np
import pandas as pd

In [21]:
# creating sample data frame
np.random.seed(42)

mu_vector1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vector1, cov_mat1, 20)

df = pd.DataFrame(class1_sample, columns=['f1','f2','f3'])
df['target']=1

mu_vector2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vector2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample, columns=['f1','f2','f3'])
df1['target'] = 0

df = pd.concat([df,df1], ignore_index=True).sort_index()
df.sample(40)

f1        f2        f3  target
32  1.296120  1.261055  1.005113       0
36  1.257550  0.925554 -0.918771       0
35  1.404051  2.886186  1.174578       0
22  0.927990  2.003533  1.361636       0
11 -1.057711  0.822545 -1.220844       1
25  1.821903  1.087047  0.700993       0
13  0.196861  0.738467  0.171368       1
12  0.208864 -1.959670 -1.328186       1
9   0.375698 -0.600639 -0.291694       1
39 -0.168678  2.142823  1.751933       0
24  0.964174  2.564644 -1.619745       0
14 -0.115648 -0.301104 -1.478522       1
1   1.523030 -0.234153 -0.234137       1
17 -0.385082 -0.676922  0.611676       1
7  -0.225776  0.067528 -1.424748       1
28  0.191506  0.498243  1.915402       0
27  1.357113  2.477894  0.481730       0
6  -0.908024 -1.412304  1.465649       1
20  0.520826  0.814341 -0.106335       0
38  0.807639  1.301547  0.965288       0
18  1.031000  0.931280 -0.839218       1
3   0.542560 -0.463418 -0.465730       1
19 -0.309212  0.331263  0.975545       1
2   1.579213  0.767435 -0.469474       1
29  1.328751  0.470240  1.513267       0
34  0.657285  0.197723  0.838714       0
26  1.091761 -0.987569  0.780328       0
8  -0.544383  0.110923 -1.150994       1
0   0.496714 -0.138264  0.647689       1
31  0.672338  0.607892 -0.463515       0
15 -0.719844 -0.460639  1.057122       1
30  1.097078  1.968645  0.297947       0
10 -0.601707  1.852278 -0.013497       1
21 -0.196207  1.812526  2.356240       0
5  -0.562288 -1.012831  0.314247       1
33  0.765413 -0.415371  0.579355       0
4   0.241962 -1.913280 -1.724918       1
23  0.354880  1.361396  2.538037       0
37  0.973486  1.060230  3.463242       0
16  0.343618 -1.763040  0.324084       1

In [23]:
## Now let's visualize our dataframe in 3d graph using plotly
import plotly.express as px

fig = px.scatter_3d(df,
                    x=df['f1'],
                    y=df['f2'],
                    z=df['f3'],
                    color = df['target'].astype('str'))

fig.update_traces(marker=dict(size=12,line=dict(width=2,color='DarkSlateGrey')),selector=dict(mode='markers'))

fig.show()

In [24]:
## Now let's work on converting our 3-d features into 2-d features using pca

### Step-01 Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])
df.describe()

f1         f2            f3    target
count  4.000000e+01  40.000000  4.000000e+01  40.00000
mean   4.440892e-17   0.000000  4.440892e-17   0.50000
std    1.012739e+00   1.012739  1.012739e+00   0.50637
min   -2.033271e+00  -1.977095 -1.712738e+00   0.00000
25%   -8.482332e-01  -0.728686 -6.683381e-01   0.00000
50%    7.106243e-02   0.069194  5.344254e-02   0.50000
75%    7.930060e-01   0.653999  5.640908e-01   1.00000
max    1.835061e+00   1.969207  2.593645e+00   1.00000

In [29]:
# step-02 Find covariance matrix
covariance_matrix = np.cov(df.iloc[:, 0:3].values, rowvar=False)
print(f"Covariance Matrix: \n{covariance_matrix}")

Covariance Matrix: 
[[1.02564103 0.35175    0.07987862]
 [0.35175    1.02564103 0.28328008]
 [0.07987862 0.28328008 1.02564103]]


In [30]:
# step-03 Find ev and evs
eigen_value, eigen_vectors = np.linalg.eig(covariance_matrix)
eigen_value, eigen_vectors

(array([1.51825759, 0.94771609, 0.6109494 ]),
 array([[-0.56014874, -0.62132881,  0.5478904 ],
        [-0.67561935, -0.04005698, -0.73616162],
        [-0.47934526,  0.78252536,  0.3973439 ]]))

In [31]:
# top 2 pc's
pc = eigen_vectors[0:2]
pc

array([[-0.56014874, -0.62132881,  0.5478904 ],
       [-0.67561935, -0.04005698, -0.73616162]])

In [32]:
tranformed_df = np.dot(df.iloc[:,0:3], pc.T)
new_df = pd.DataFrame(tranformed_df, columns=['pc1', 'pc2'])
new_df['target'] = df['target'].values

In [33]:
new_df.head()

pc1       pc2  target
0  0.416681 -0.206204       1
1 -0.708108 -0.595720       1
2 -1.364202 -0.535582       1
3  0.040356  0.443141       1
4  0.427521  1.532677       1